//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impostor.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impostor.Server.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your game to play in this lobby..
        /// </summary>
        internal static string DisconnectMessages_ClientOutdated {
            get {
                return ResourceManager.GetString("DisconnectMessages.ClientOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game version is too new for this lobby. If you want to join this lobby you need to downgrade your client..
        /// </summary>
        internal static string DisconnectMessages_ClientTooNew {
            get {
                return ResourceManager.GetString("DisconnectMessages.ClientTooNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game you tried to join is being destroyed. Please create a new game..
        /// </summary>
        internal static string DisconnectMessages_Destroyed {
            get {
                return ResourceManager.GetString("DisconnectMessages.Destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an internal server error. Check the server console for more information. Please report the issue on the Impostor GitHub if it keeps happening..
        /// </summary>
        internal static string DisconnectMessages_Error {
            get {
                return ResourceManager.GetString("DisconnectMessages.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your client is requesting host authority, which is not enabled on this Impostor server..
        /// </summary>
        internal static string DisconnectMessages_HostAuthorityUnsupported {
            get {
                return ResourceManager.GetString("DisconnectMessages.HostAuthorityUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, UDP Matchmaking is no longer supported.\nSee &lt;link=https://github.com/Impostor/Impostor/blob/master/docs/Upgrading.md#impostor-190&gt;Impostor documentation&lt;/link&gt; on how to migrate to HTTP Matchmaking.
        /// </summary>
        internal static string DisconnectMessages_UdpMatchmakingUnsupported {
            get {
                return ResourceManager.GetString("DisconnectMessages.UdpMatchmakingUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Impostor/Impostor/blob/master/docs/Upgrading.md.
        /// </summary>
        internal static string DisconnectMessages_UpgradingDocsLink {
            get {
                return ResourceManager.GetString("DisconnectMessages.UpgradingDocsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username contains illegal characters, please remove them..
        /// </summary>
        internal static string DisconnectMessages_UsernameIllegalCharacters {
            get {
                return ResourceManager.GetString("DisconnectMessages.UsernameIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is too long, please make it shorter..
        /// </summary>
        internal static string DisconnectMessages_UsernameLength {
            get {
                return ResourceManager.GetString("DisconnectMessages.UsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your game to play on this server..
        /// </summary>
        internal static string DisconnectMessages_VersionClientTooOld {
            get {
                return ResourceManager.GetString("DisconnectMessages.VersionClientTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your client is too new, please update your Impostor server to play..
        /// </summary>
        internal static string DisconnectMessages_VersionServerTooOld {
            get {
                return ResourceManager.GetString("DisconnectMessages.VersionServerTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your client version is unsupported, please update your Game and/or Impostor server..
        /// </summary>
        internal static string DisconnectMessages_VersionUnsupported {
            get {
                return ResourceManager.GetString("DisconnectMessages.VersionUnsupported", resourceCulture);
            }
        }
    }
}
