namespace Impostor.Api.Innersloth.Net.Objects.Systems
{
    public enum SystemTypes : byte
    {
        Hallway,
        Storage,
        Cafeteria,
        Reactor,
        UpperEngine,
        Nav,
        Admin,
        Electrical,
        LifeSupp,
        Shields,
        MedBay,
        Security,
        Weapons,
        LowerEngine,
        Comms,
        ShipTasks,
        Doors,
        Sabotage,
        Decontamination,
        Launchpad,
        LockerRoom,
        Laboratory,
        Balcony,
        Office,
        Greenhouse,
    }
}