namespace Impostor.Api.Net.Inner
{
    public enum RpcCalls : byte
    {
        PlayAnimation = 0,
        CompleteTask = 1,
        SyncSettings = 2,
        SetInfected = 3,
        Exiled = 4,
        CheckName = 5,
        SetName = 6,
        CheckColor = 7,
        SetColor = 8,
        ReportDeadBody = 11,
        MurderPlayer = 12,
        SendChat = 13,
        StartMeeting = 14,
        SetScanner = 15,
        SendChatNote = 16,
        SetStartCounter = 18,
        EnterVent = 19,
        ExitVent = 20,
        SnapTo = 21,
        Close = 22,
        VotingComplete = 23,
        CastVote = 24,
        ClearVote = 25,
        AddVote = 26,
        CloseDoorsOfType = 27,
        RepairSystem = 28,
        SetTasks = 29,
        ClimbLadder = 31,
        UsePlatform = 32,
        SendQuickChat = 33,
        BootFromVent = 34,
        UpdateSystem = 35,
        SetLevel = 38,
        SetHat = 39,
        SetSkin = 40,
        SetPet = 41,
        SetVisor = 42,
        SetNamePlate = 43,
        SetRole = 44,
        ProtectPlayer = 45,
        Shapeshift = 46,
        CheckMurder = 47,
        CheckProtect = 48,
    }
}
