name: CI Plugin

on:
  push:
    branches:
      - preview
    paths:
      - '.github/workflows/ci-plugin.yml'
      - 'src/Plugins/**'
      - 'build-plugin.cake'
  pull_request:
    branches:
      - preview
    paths:
      - '.github/workflows/ci-plugin.yml'
      - 'src/Plugins/**'
      - 'build-plugin.cake'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Next-Fast' 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v3
        with:
          verbosity: Minimal
          script-path: ./build-plugin.cake

